# Generated by Django 5.1.5 on 2025-03-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikdip', '0004_delete_customerdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Italian_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('original_price', models.IntegerField()),
                ('menu_image', models.ImageField(upload_to='menu_images')),
            ],
        ),
    ]
