# Generated by Django 5.1.5 on 2025-03-26 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikdip', '0009_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='cart_images/')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('indian', 'Indian Cuisine'), ('italian', 'Italian Cuisine'), ('dessert', 'Desserts'), ('snack', 'Snacks'), ('drink', 'Drinks')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
