# Generated by Django 5.1.5 on 2025-04-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikdip', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
