# Generated by Django 5.1.5 on 2025-03-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikdip', '0003_indian_menu_delete_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetail',
        ),
    ]
