# Generated by Django 5.1.5 on 2025-03-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikdip', '0005_italian_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Italian_menu',
        ),
    ]
